[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
proof_verifier = "FLfi8rshUqV8cn71Z1nj29bFLmDdAhiHsVBoqLvhia1F"
proofxi = "3wqZbXRsECPBib3sfuHGFtZis9WP9JENm3JHxqBtgNCE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "keypairs/devnet.json"

[scripts]
test = "tsx scripts/verify-proof.ts"
